language: node_js
node_js:
  - lts/*
matrix:
  include:
    - name: "react 16.8"
      env: REACT_VERSION=^16.8.0
    - name: "react 16.9"
      env: REACT_VERSION=^16.9.0
script:
  - |
    bash -c "
      set -eo pipefail
      for PKG in react react-dom react-test-renderer; do
        node scripts/change_react_deps_version.js "$REACT_VERSION"
      done
      cat package.json
      yarn
      yarn test --coverage
      cat ./coverage/lcov.info | yarn coveralls
    "
